### ISSUE TITLE
Add client/server communication states/commands

### ISSUE THREAD

**Issue by ljleb** [XavierCL/UnitWorld-solo#5]
# general types
* ### Vector2D
```json
{
  "x": double,
  "y": double
}
```

* ### Singuity
```json
{
  "id": Guid,
  "playerId": Guid,
  "position": Vector2D,
  "speed": Vector2D,
  "destination": Vector2D | null
}
```

* ### Player
```json
{
  "id": Guid
}
```

# requests
* ### move singuities
```json
{
  "action": "moveUnits",
  "arguments": {
    "destination": Vector2D,
    "singuityIds": Guid[]
  }
}
```

# states
* ### update a game
```json
{
  "action": "update",
  "arguments": {
    "singuities": Singuity[],
    "players": Player[],
    "currentPlayerId": Guid
  }
}
```

**Comment by ljleb** [comment]
In a future update, I suggest merging `Unit` and `Spawner` into a single kind of thing having the `"type"` property, to generalise the representation of units. This would ease the developpement of new types of units, i.e. units that teleport (`"type": "teleport"`), moving spawners (`"type": "movingSpawner"`), rock-paper-scissors (`"type": "rock"`), ...

**Comment by XavierCL** [comment]
I wouldn't say it would "ease" the addition of new units, since now the parsers will have to dynamically parse the attributes of the unit array. I'd prefer having multiple arrays, all getting parsed in a fixed but different ways. This also allows for scaling in the form of adding new arrays when new units are created.

Obviously in both case the server and client game versions must match perfectly, so that's no game changer

**Comment by XavierCL** [comment]
For the moment I'll be merging "gameStart" and "gameUpdate" since currently players are added dynamically to the game. The arguments of the "gameUpdate" will simply have both a singuity and a player array.

**Comment by XavierCL** [comment]
We also need to provide each client with which player he is in it's complete game state.
